server:
  port: 8888
spring:
  servlet:
    multipart:
      max-request-size: 2048MB
      max-file-size: 2048MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.68.200:3306/cfd_oa_rh?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  data:
    redis:
      host: 192.168.68.200
      password:
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  key: 'JHiuFHDHUjiuuds!gsduadfdapofds;fkjrfeuihgre'
  expire: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zqhyz.controller
    - group: '检活'
      paths-to-match: '/check/**'
      packages-to-scan: com.zqhyz.controller
knife4j:
  enable: true
  setting:
    language: zh_cn